name: rotate
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  aviation_entities:
    path: local_packages/aviation_entities
  aviation_units:
    path: local_packages/aviation_units
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  domain_model:
    path: local_packages/domain_model
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  logger: ^1.1.0
  navigation_data:
    path: local_packages/navigation_data
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  syncfusion_flutter_pdf: ^19.4.52-beta
  json_annotation: ^4.4.0
  theming:
    path: local_packages/theming

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  lint: ^1.8.2
  test: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: LexendDeca
      fonts:
        - asset: packages/theming/fonts/LexendDeca-Regular.ttf
          weight: 400
