name: roster_parser

environment:
    sdk: ">=2.14.0<3.0.0"

dependencies:
    freezed_annotation: ^1.1.0
    sembast: ^3.2.0
    get_it: ^7.2.0
    aviation_entities:
        path: ../aviation_entities
    aviation_units:
        path: ../aviation_units
    rotate_entities:
        path: ../rotate_entities
    flutter:
        sdk: flutter
    syncfusion_flutter_pdf: ^19.4.52-beta

dev_dependencies:
    build_runner: ^2.1.4
    freezed: ^1.1.0
    lint: ^1.8.2
    test: ^1.19.0

flutter:
  assets:
    - packages/roster_parser/data/airline_configs/CFG/
