/// Flutter icons NavAidIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavAidIcons
///      fonts:
///       - asset: fonts/NavAidIcons.ttf
///
///
///
///
/// Navaid svg from https://iconduck.com/search?query=navaid
import 'package:flutter/widgets.dart';

class NavAidIcons {
  NavAidIcons._();

  static const _kFontFam = 'NavAidIcons';

  static const IconData vortac = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData vordme = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData vor = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData tacan = IconData(0xe804, fontFamily: _kFontFam);
}
