name: rotate_entities

environment:
    sdk: ">=2.14.0<3.0.0"

dependencies:
    aviation_entities:
        path: ../aviation_entities
    aviation_units:
        path: ../aviation_units
    freezed_annotation: ^1.1.0
    get_it: ^7.2.0
    json_serializable: ^6.1.4
    json_annotation: ^4.4.0
    path: ^1.8.0
    sembast: ^3.2.0

dev_dependencies:
    build_runner: ^2.1.4
    freezed: ^1.1.0
    lint: ^1.8.2
    test: ^1.19.0
