name: domain_model
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  aviation_entities:
    path: ../aviation_entities
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.6
  freezed: ^1.1.0
  lint: ^1.8.2
  test: ^1.16.0
