name: domain_model
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  aviation_entities:
    path: ../aviation_entities
<<<<<<< HEAD
  freezed_annotation: ^1.1.0
=======
  aviation_units:
    path: ../aviation_units
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_serializable: ^6.1.4
  path: ^1.8.0
  sembast: ^3.2.0
>>>>>>> rotate/project_structure

dev_dependencies:
  build_runner: ^2.0.6
  freezed: ^1.1.0
  lint: ^1.8.2
  test: ^1.16.0
