name: Flutter_Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install and set Flutter version #https://github.com/subosito/flutter-action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Pub get
        run: flutter pub get

      - name: Flutter doctor
        run: flutter doctor

      - name: Testing main project 
        run: flutter test test

      - name: Pub get aviation_units
        working-directory: ./local_packages/aviation_units
        run: flutter pub get

      - name: Pub get aviation_entities
        working-directory: ./local_packages/aviation_entities
        run: flutter pub get

      - name: Pub get navigation_data
        working-directory: ./local_packages/navigation_data
        run: flutter pub get

      - name: Testing packages 
        run: flutter test local_packages

      # - name: Analyzing main project 
      #   run: flutter analyze lib

      - name: Analyzing packages 
        run: flutter analyze local_packages

